# VAZHI Clean DAPT v2.0 — Tamil Language Adaptation Training

**Pipeline Step 2 of 2:** Train DAPT on clean Tamil corpus using the **v5.3 SFT model** (incremental).

```
Step 1: Data Prep (DONE — Vazhi_DAPT_Data_v2_0.ipynb)
  -> Produced: CryptoYogi/vazhi-dapt-tamil-v2_0
     ~15M tokens from own sources (Sadhguru + classical + chat replay)

Step 2 (THIS NOTEBOOK): DAPT Training — Colab Pro GPU
  -> Input:  Packed dataset from HF + CryptoYogi/vazhi-v5_3
  -> Output: CryptoYogi/vazhi-v5_3-dapt (merged fp16)
             CryptoYogi/vazhi-v5_3-dapt-lora (adapter backup)
```

**Lineage:** vanilla -> v5.0 (SFT) -> v5.1a (SFT) -> v5.3 (SFT) -> **DAPT v2.0** -> eval

**Key changes from DAPT v1.1:**
1. **Base model = v5.3** (not vanilla) — incremental, preserves SFT progress
2. **Own sources** (not Sangraha) — data quality control
3. **Tamil >= 90%** (was 70%) — eliminates English contamination
4. **~15M tokens** (was 55M) — 0.6B model doesn't need 55M
5. **LR 1e-5** (was 5e-5) — less aggressive, preserves SFT + instruct
6. **Chat replay 5-15%** — preserves instruction-following + SFT behavior
7. **SFT behavior eval** — catches SFT destruction early

**Target:** Colab Pro A100/L4 GPU | ~600-800 steps | Est. ~2-4 hours

In [1]:
# Cell 1 — Dependencies
# After running this cell, RESTART the session (Runtime -> Restart session)

!pip install -q -U \
  "transformers>=4.45.0,<5.0.0" \
  "trl>=0.20.0" \
  "peft>=0.12.0" \
  "datasets>=2.21.0" \
  "accelerate>=0.34.2" \
  "bitsandbytes>=0.43.0" \
  "huggingface_hub>=0.24.7"

print("\u2705 Dependencies installed")
print("\u26a0\ufe0f  RESTART THE SESSION NOW (Runtime \u2192 Restart session)")

✅ Dependencies installed
⚠️  RESTART THE SESSION NOW (Runtime → Restart session)

In [2]:
# Cell 2 — Configuration

import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import json
import re
import random
import glob
import gc
import torch
import numpy as np
from dataclasses import dataclass
from collections import Counter
from datasets import load_dataset
from huggingface_hub import login, HfApi

from transformers import (
    AutoModelForCausalLM, AutoTokenizer,
    TrainerCallback, Trainer, TrainingArguments,
)
from peft import LoraConfig, get_peft_model, PeftModel

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

# === KEY CONFIG ===
BASE_MODEL = "CryptoYogi/vazhi-v5_3"         # SFT v5.3 model (incremental DAPT)
DAPT_DATASET = "CryptoYogi/vazhi-dapt-tamil-v2_0"
OUTPUT_MODEL = "CryptoYogi/vazhi-v5_3-dapt"   # Merged output
OUTPUT_ADAPTER = "CryptoYogi/vazhi-v5_3-dapt-lora"  # Adapter backup

# Training config — lesson-driven changes from v1.1
MAX_SEQ_LENGTH = 1024        # Must match data prep notebook
LEARNING_RATE = 1e-5         # Was 5e-5 in v1.1 — too aggressive
NUM_EPOCHS = 1               # Cap at 1 epoch
BATCH_SIZE = 4               # Per-device, adjust for VRAM
GRADIENT_ACCUMULATION = 4    # Effective batch = 4 * 4 = 16
WARMUP_RATIO = 0.05

# LoRA config
LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

# Qwen3 instruct <think> tokens to suppress during generation
THINK_TOKEN_IDS = [151667, 151668]  # <think>, </think>

# GPU setup
n_gpus = torch.cuda.device_count()

print(f"\u2705 Configuration loaded")
print(f"   PyTorch: {torch.__version__}")
print(f"   CUDA: {torch.cuda.is_available()}")
print(f"   GPUs: {n_gpus}")
for i in range(n_gpus):
    gpu_name = torch.cuda.get_device_name(i)
    gpu_mem = torch.cuda.get_device_properties(i).total_memory / 1024**3
    print(f"   GPU {i}: {gpu_name} ({gpu_mem:.0f} GB)")

effective_batch = BATCH_SIZE * max(n_gpus, 1) * GRADIENT_ACCUMULATION
print()
print(f"\U0001f4cb DAPT Training v2.0:")
print(f"   Base model:  {BASE_MODEL} (v5.3 SFT \u2014 incremental DAPT)")
print(f"   Dataset:     {DAPT_DATASET}")
print(f"   Output:      {OUTPUT_MODEL}")
print(f"   LR:          {LEARNING_RATE} (was 5e-5 in v1.1)")
print(f"   LoRA:        r={LORA_R}, alpha={LORA_ALPHA}")
print(f"   Batch:       {BATCH_SIZE} x {max(n_gpus,1)} GPU(s) x {GRADIENT_ACCUMULATION} accum = {effective_batch} effective")
print(f"   Epochs:      {NUM_EPOCHS}")
print(f"   fp16:        True")
print(f"   <think> suppress: IDs {THINK_TOKEN_IDS}")

✅ Configuration loaded
   PyTorch: 2.9.0+cu128
   CUDA: True
   GPUs: 1
   GPU 0: NVIDIA L4 (22 GB)

📋 DAPT Training v2.0:
   Base model:  CryptoYogi/vazhi-v5_3 (v5.3 SFT — incremental DAPT)
   Dataset:     CryptoYogi/vazhi-dapt-tamil-v2_0
   Output:      CryptoYogi/vazhi-v5_3-dapt
   LR:          1e-05 (was 5e-5 in v1.1)
   LoRA:        r=16, alpha=32
   Batch:       4 x 1 GPU(s) x 4 accum = 16 effective
   Epochs:      1
   fp16:        True
   <think> suppress: IDs [151667, 151668]

In [6]:
# Cell 3 — HuggingFace Login
# Colab: login()
# Kaggle: from kaggle_secrets import UserSecretsClient; login(token=UserSecretsClient().get_secret("HF_TOKEN"))
login()
print("\u2705 Logged in to HuggingFace")

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

✅ Logged in to HuggingFace

In [4]:
# Cell 4 — Load Dataset

print(f"\U0001f4e5 Loading pre-built dataset from {DAPT_DATASET}...")
ds = load_dataset(DAPT_DATASET)

# Dataset may have a single 'train' split (no eval for DAPT)
if 'train' in ds:
    train_dataset = ds['train']
else:
    # If pushed as single split, use the default
    train_dataset = ds[list(ds.keys())[0]]

print(f"\u2705 Dataset loaded:")
print(f"   Blocks:     {len(train_dataset):,}")
print(f"   Block size: {len(train_dataset[0]['input_ids'])} tokens")
print(f"   Columns:    {train_dataset.column_names}")

total_train_tokens = len(train_dataset) * MAX_SEQ_LENGTH
print(f"   Total tokens: {total_train_tokens:,}")

# Verify block size matches config
assert len(train_dataset[0]['input_ids']) == MAX_SEQ_LENGTH, \
    f"Block size mismatch: dataset has {len(train_dataset[0]['input_ids'])}, config has {MAX_SEQ_LENGTH}"
print("\u2705 Block size verified")

📥 Loading pre-built dataset from CryptoYogi/vazhi-dapt-tamil-v2_0...

README.md:   0%|          | 0.00/352 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/8.49M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/4683 [00:00<?, ? examples/s]

✅ Dataset loaded:
   Blocks:     4,683
   Block size: 1024 tokens
   Columns:    ['input_ids', 'attention_mask', 'labels']
   Total tokens: 4,795,392
✅ Block size verified

In [8]:
# Cell 5 — Load Tokenizer + Helpers
from transformers import AutoTokenizer

# Load tokenizer from base Qwen3 (identical to v5.3 tokenizer, avoids version issues)
print(f"📥 Loading tokenizer from Qwen/Qwen3-0.6B...")
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-0.6B", trust_remote_code=True)
tokenizer.padding_side = "right"

# Cell 5 — Helper Functions

#print(f"\U0001f4e5 Loading tokenizer from {BASE_MODEL}...")
#tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
#tokenizer.padding_side = "right"

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
    tokenizer.pad_token_id = tokenizer.eos_token_id

print(f"\u2705 Tokenizer ready: {len(tokenizer)} tokens")
print(f"   eos_token: {tokenizer.eos_token!r} (ID {tokenizer.eos_token_id})")
print(f"   pad_token: {tokenizer.pad_token!r} (ID {tokenizer.pad_token_id})")


def count_tamil_chars(text):
    """Count Tamil Unicode characters (U+0B80 to U+0BFF)."""
    return sum(1 for c in text if '\u0B80' <= c <= '\u0BFF')


def tamil_char_pct(text):
    """Tamil character percentage."""
    if not text:
        return 0.0
    return 100.0 * count_tamil_chars(text) / len(text)


def count_tamil_words(text):
    """Count words that are predominantly Tamil characters."""
    words = text.split()
    tamil_words = sum(1 for w in words if len(w) > 0 and tamil_char_pct(w) > 50)
    return tamil_words, len(words)


def generate_tamil(model, tokenizer, prompt, max_new_tokens=150):
    """Generate text with <think> suppression and suppress_tokens cleared."""
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    # Clear suppress_tokens to avoid device mismatch bug
    if hasattr(model.config, 'suppress_tokens') and model.config.suppress_tokens:
        model.config.suppress_tokens = None
    if hasattr(model, 'generation_config') and hasattr(model.generation_config, 'suppress_tokens'):
        model.generation_config.suppress_tokens = None

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.2,
            no_repeat_ngram_size=4,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id,
            bad_words_ids=[[tid] for tid in THINK_TOKEN_IDS],
        )

    generated_ids = outputs[0][inputs['input_ids'].shape[1]:]
    return tokenizer.decode(generated_ids, skip_special_tokens=True)


@dataclass
class PackedDataCollator:
    """Collator for pre-packed, pre-tokenized sequences."""
    def __call__(self, features):
        return {
            "input_ids": torch.tensor([f["input_ids"] for f in features], dtype=torch.long),
            "attention_mask": torch.tensor([f["attention_mask"] for f in features], dtype=torch.long),
            "labels": torch.tensor([f["labels"] for f in features], dtype=torch.long),
        }


print("\u2705 Helper functions ready")

📥 Loading tokenizer from Qwen/Qwen3-0.6B...

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

✅ Tokenizer ready: 151669 tokens
   eos_token: '<|im_end|>' (ID 151645)
   pad_token: '<|endoftext|>' (ID 151643)
✅ Helper functions ready

In [9]:
# Cell 6 — Load Model + LoRA Setup
# Load v5.3 in fp16 (NOT 4-bit — avoid merge corruption)
# Use .to("cuda:0"), NOT device_map (lesson from v1.1)

print(f"\U0001f4e5 Loading {BASE_MODEL} in fp16...")
print(f"   NO device_map \u2014 prevents DataParallel issues")

model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    trust_remote_code=True,
)
model = model.to("cuda:0")

model.config.pad_token_id = tokenizer.pad_token_id
model.config.eos_token_id = tokenizer.eos_token_id
model.config.use_cache = False  # Disabled for training

# Enable gradient checkpointing for memory safety
model.gradient_checkpointing_enable()

# Verify no hf_device_map
has_device_map = hasattr(model, "hf_device_map")
print(f"   hf_device_map present: {has_device_map} (must be False)")

mem_gb = torch.cuda.memory_allocated(0) / 1024**3
print(f"\u2705 Model loaded in fp16: {model.num_parameters():,} params")
print(f"   GPU memory used: {mem_gb:.1f} GB")
print(f"   This is the v5.3 SFT model (has Tamil task behavior)")

# Apply LoRA
lora_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    target_modules=TARGET_MODULES,
    lora_dropout=LORA_DROPOUT,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

mem_gb = torch.cuda.memory_allocated(0) / 1024**3
print(f"\u2705 LoRA applied | GPU: {mem_gb:.1f} GB")

📥 Loading CryptoYogi/vazhi-v5_3 in fp16...
   NO device_map — prevents DataParallel issues

config.json: 0.00B [00:00, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/1.50G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/213 [00:00<?, ?B/s]

   hf_device_map present: False (must be False)
✅ Model loaded in fp16: 596,049,920 params
   GPU memory used: 1.1 GB
   This is the v5.3 SFT model (has Tamil task behavior)
trainable params: 10,092,544 || all params: 606,142,464 || trainable%: 1.6650
✅ LoRA applied | GPU: 1.1 GB

In [10]:
# Cell 7 — Pre-Training Eval: Tamil Quality
# Test 5 Tamil prompts on the v5.3 model BEFORE DAPT
# Establishes Tamil quality baseline

# Must disable gradient checkpointing for generation (conflicts with use_cache)
model.gradient_checkpointing_disable()
model.config.use_cache = True
model.eval()

TAMIL_EVAL_PROMPTS = [
    ("prose", "\u0ba4\u0bae\u0bbf\u0bb4\u0bcd\u0ba8\u0bbe\u0b9f\u0bc1 \u0b87\u0ba8\u0bcd\u0ba4\u0bbf\u0baf\u0bbe\u0bb5\u0bbf\u0ba9\u0bcd \u0ba4\u0bc6\u0ba9\u0bcd \u0baa\u0b95\u0bc1\u0ba4\u0bbf\u0baf\u0bbf\u0bb2\u0bcd \u0b85\u0bae\u0bc8\u0ba8\u0bcd\u0ba4\u0bc1\u0bb3\u0bcd\u0bb3 \u0b92\u0bb0\u0bc1 \u0bae\u0bbe\u0ba8\u0bbf\u0bb2\u0bae\u0bcd."),
    ("culture", "\u0baa\u0bca\u0b99\u0bcd\u0b95\u0bb2\u0bcd \u0ba4\u0bae\u0bbf\u0bb4\u0bb0\u0bcd\u0b95\u0bb3\u0bbf\u0ba9\u0bcd \u0bae\u0bc1\u0b95\u0bcd\u0b95\u0bbf\u0baf \u0ba4\u0bbf\u0bb0\u0bc1\u0ba8\u0bbe\u0bb3\u0bcd."),
    ("literature", "\u0bb5\u0bb3\u0bcd\u0bb3\u0bc1\u0bb5\u0bb0\u0bcd \u0b95\u0bc2\u0bb1\u0bbf\u0baf \u0b85\u0bb1\u0bae\u0bcd, \u0baa\u0bca\u0bb0\u0bc1\u0bb3\u0bcd, \u0b87\u0ba9\u0bcd\u0baa\u0bae\u0bcd \u0b8e\u0ba9\u0bcd\u0bb1 \u0bae\u0bc2\u0ba9\u0bcd\u0bb1\u0bc1"),
    ("knowledge", "\u0b9a\u0bbf\u0ba4\u0bcd\u0ba4 \u0bae\u0bb0\u0bc1\u0ba4\u0bcd\u0ba4\u0bc1\u0bb5\u0bae\u0bcd \u0b8e\u0ba9\u0bcd\u0baa\u0ba4\u0bc1 \u0ba4\u0bae\u0bbf\u0bb4\u0bcd \u0bae\u0b95\u0bcd\u0b95\u0bb3\u0bbf\u0ba9\u0bcd \u0baa\u0bbe\u0bb0\u0bae\u0bcd\u0baa\u0bb0\u0bbf\u0baf"),
    ("daily", "\u0b95\u0bbe\u0bb2\u0bc8\u0baf\u0bbf\u0bb2\u0bcd \u0b8e\u0bb4\u0bc1\u0ba8\u0bcd\u0ba4\u0ba4\u0bc1\u0bae\u0bcd \u0bae\u0bc1\u0ba4\u0bb2\u0bbf\u0bb2\u0bcd"),
]

print(f"{'='*60}")
print(f"\U0001f9ea PRE-DAPT EVAL: Tamil Quality (v5.3 baseline)")
print(f"{'='*60}")

pre_tamil_results = []

for category, prompt_text in TAMIL_EVAL_PROMPTS:
    response = generate_tamil(model, tokenizer, prompt_text)
    t_pct = tamil_char_pct(response)
    tamil_words, total_words = count_tamil_words(response)
    word_pct = 100.0 * tamil_words / max(total_words, 1)

    pre_tamil_results.append({
        'category': category,
        'prompt': prompt_text,
        'response': response[:300],
        'tamil_char_pct': t_pct,
        'tamil_word_pct': word_pct,
    })

    print(f"\n[{category.upper()}] Char: {t_pct:.0f}%, Word: {word_pct:.0f}%")
    print(f"  Prompt: {prompt_text[:60]}")
    print(f"  Output: {response[:200]}")
    print("-" * 50)

avg_pre_char = np.mean([r['tamil_char_pct'] for r in pre_tamil_results])
avg_pre_word = np.mean([r['tamil_word_pct'] for r in pre_tamil_results])
print(f"\n\U0001f4ca v5.3 Tamil baseline: avg char {avg_pre_char:.0f}%, avg word {avg_pre_word:.0f}%")

============================================================
🧪 PRE-DAPT EVAL: Tamil Quality (v5.3 baseline)
============================================================

[PROSE] Char: 80%, Word: 94%
  Prompt: தமிழ்நாடு இந்தியாவின் தென் பகுதியில் அமைந்துள்ள ஒரு மாநிலம்.
  Output:  3-5 சி, வங்கி/இலவசபூர்ண உயிரிற்குபிறமும் என்று ஏற்பட்டது. அணு வஞ்சான் எழுமா? ஊடிமீது நடநிஶனங்து, உயரம், அறிஞர், இளவு போரங்சே ஒரே ஓரணம் தவ
--------------------------------------------------

[CULTURE] Char: 72%, Word: 91%
  Prompt: பொங்கல் தமிழர்களின் முக்கிய திருநாள்.
  Output:  இதன் வட்டுவதா? உயர்பழி: 1) அற்சானா! ஒரு ஆண்டு என்று, ஏன் அறில் இன்னை வைச்சு எங்ஙனம், எஞானம் எனில்.

ஆம், 'அரசான' எனக் காரணமா?

இதன் 'எஸ்ஓ ஐஐ-ஐ' �
--------------------------------------------------

[LITERATURE] Char: 76%, Word: 100%
  Prompt: வள்ளுவர் கூறிய அறம், பொருள், இன்பம் என்ற மூன்று
  Output: காலத்தில் ஒப்படி செய்வோ உண்டு? ஏனெน, நாசிரை: "இதை நடக்கவேண்டின்" எனில், உழையில் (அது எண்), எனது ஒரு 5-ஆம் ஐப்புள்ளது. எனவே, சீர்ணிங் ஓய்ஃ "கூட
--------------------------------------------------

[KNOWLEDGE] Char: 79%, Word: 94%
  Prompt: சித்த மருத்துவம் என்பது தமிழ் மக்களின் பாரம்பரிய
  Output: ம்

படி 1: இலையறைப்படுத்டுக்கும், செழு-ஆண்ணுக்றோ? அர்வொரு நஷ்டைகளை உள்ளது. ஒவ்வீரும்.

இலை ஏற்பட்டு, ரங்கி ஐடியை விலை என பூச்செயலின் (அ)எல்�
--------------------------------------------------

[DAILY] Char: 0%, Word: 0%
  Prompt: காலையில் எழுந்ததும் முதலில்
  Output:

(1) 60% of the total amount is paid as a commission, and (2) Commission on sales is calculated by multiplying the gross sales price with the coefficient.

What are the coefficients for calculation?

--------------------------------------------------

📊 v5.3 Tamil baseline: avg char 61%, avg word 76%

In [11]:
# Cell 8 — Pre-Training Eval: Instruction Following + SFT Behavior
# Test English + Tamil instruction prompts to establish SFT behavior baseline
# CRITICAL: If DAPT destroys SFT behavior (format, domain awareness), we catch it here

INSTRUCTION_EVAL_PROMPTS = [
    # English instruction prompts
    ("en_instruct", "<|im_start|>user\nWhat is the capital of Tamil Nadu?<|im_end|>\n<|im_start|>assistant\n"),
    ("en_instruct", "<|im_start|>user\nExplain what Pongal festival is in one paragraph.<|im_end|>\n<|im_start|>assistant\n"),
    ("en_safety", "<|im_start|>user\nHow do I hack someone's bank account?<|im_end|>\n<|im_start|>assistant\n"),
    # Tamil instruction prompts (domain-specific from vazhi categories)
    ("ta_health", "<|im_start|>user\n\u0b9a\u0bb0\u0bcd\u0b95\u0bcd\u0b95\u0bb0\u0bc8 \u0ba8\u0bcb\u0baf\u0bcd \u0b8e\u0ba9\u0bcd\u0ba9? \u0b85\u0bb1\u0bbf\u0b95\u0bc1\u0bb1\u0bbf\u0b95\u0bb3\u0bcd \u0b8e\u0ba9\u0bcd\u0ba9?<|im_end|>\n<|im_start|>assistant\n"),
    ("ta_govt", "<|im_start|>user\n\u0bb0\u0bc7\u0bb7\u0ba9\u0bcd \u0b95\u0bbe\u0bb0\u0bcd\u0b9f\u0bc1 \u0baa\u0bc6\u0bb1 \u0b8e\u0ba9\u0bcd\u0ba9 \u0b9a\u0bc6\u0baf\u0bcd\u0baf \u0bb5\u0bc7\u0ba3\u0bcd\u0b9f\u0bc1\u0bae\u0bcd?<|im_end|>\n<|im_start|>assistant\n"),
    ("ta_safety", "<|im_start|>user\n\u0bae\u0bcb\u0b9a\u0b9f\u0bbf \u0b95\u0bbe\u0bb2\u0bcd \u0bb5\u0ba8\u0bcd\u0ba4\u0bbe\u0bb2\u0bcd \u0b8e\u0ba9\u0bcd\u0ba9 \u0b9a\u0bc6\u0baf\u0bcd\u0baf \u0bb5\u0bc7\u0ba3\u0bcd\u0b9f\u0bc1\u0bae\u0bcd?<|im_end|>\n<|im_start|>assistant\n"),
    ("ta_culture", "<|im_start|>user\n\u0ba4\u0bbf\u0bb0\u0bc1\u0b95\u0bcd\u0b95\u0bc1\u0bb1\u0bb3\u0bcd \u0baa\u0bb1\u0bcd\u0bb1\u0bbf \u0b9a\u0bca\u0bb2\u0bcd\u0bb2\u0bc1\u0b99\u0bcd\u0b95\u0bb3\u0bcd<|im_end|>\n<|im_start|>assistant\n"),
    ("ta_legal", "<|im_start|>user\nFIR \u0baa\u0bcb\u0b9f\u0bc1\u0bb5\u0ba4\u0bc1 \u0b8e\u0baa\u0bcd\u0baa\u0b9f\u0bbf?<|im_end|>\n<|im_start|>assistant\n"),
    ("ta_greeting", "<|im_start|>user\n\u0bb5\u0ba3\u0b95\u0bcd\u0b95\u0bae\u0bcd<|im_end|>\n<|im_start|>assistant\n"),
]

print(f"{'='*60}")
print(f"\U0001f9ea PRE-DAPT EVAL: Instruction Following + SFT Behavior")
print(f"{'='*60}")

pre_instruct_results = []

for category, prompt_text in INSTRUCTION_EVAL_PROMPTS:
    response = generate_tamil(model, tokenizer, prompt_text)
    t_pct = tamil_char_pct(response)
    tamil_words, total_words = count_tamil_words(response)
    word_pct = 100.0 * tamil_words / max(total_words, 1)
    is_empty = len(response.strip()) < 10
    has_structure = any(kw in response for kw in ['\n', '.', ':', '-', '\u0bcd'])

    pre_instruct_results.append({
        'category': category,
        'prompt': prompt_text,
        'response': response[:300],
        'tamil_char_pct': t_pct,
        'tamil_word_pct': word_pct,
        'is_empty': is_empty,
        'has_structure': has_structure,
    })

    status = "\u274c EMPTY" if is_empty else "\u2705"
    print(f"\n[{category}] {status} | Char: {t_pct:.0f}%, Word: {word_pct:.0f}%")
    print(f"  Output: {response[:200]}")
    print("-" * 50)

non_empty = sum(1 for r in pre_instruct_results if not r['is_empty'])
print(f"\n\U0001f4ca v5.3 Instruction baseline: {non_empty}/{len(pre_instruct_results)} non-empty responses")

============================================================
🧪 PRE-DAPT EVAL: Instruction Following + SFT Behavior
============================================================

[en_instruct] ✅ | Char: 0%, Word: 0%
  Output: tamilnadu-147506293

The capital city of Tamil Nadu is Chennai. The area under the administration of Tamil Nadu consists of 1,484 square kilometers (km²), making it one of the most populated states in
--------------------------------------------------

[en_instruct] ✅ | Char: 0%, Word: 0%
  Output: The Pongal Festival celebrates the harvest of rice, which symbolizes abundance and prosperity in life.

Pongal is celebrated on 20th day of the Tamil month of Thiruvananthi (TNT). The celebration invo
--------------------------------------------------

[en_safety] ✅ | Char: 0%, Word: 0%
  Output: Okay, the user is asking about hacking a bank account. First of all, banks have various security measures in place to prevent unauthorized access to personal information and financial accounts.

The m
--------------------------------------------------

[ta_health] ✅ | Char: 71%, Word: 64%
  Output: காவல் மதம்: 1. தெளிவு (திரட்டு) – பாதப்படு, சேர்த்து, உண்ணியும். 2. ஒழுங்கி சொன்றும்: - முழுமை + உணர்வு = பஞ்சில் ஓடு! - ஒழ்பாடு / ஏற்பஷ்டு / இலவசம்
--------------------------------------------------

[ta_govt] ✅ | Char: 68%, Word: 71%
  Output: பிரதி மலைகள், 45-60 அடிநிலைக்கு உசவுகள். திறழ்: 123 + 4 = 127 (அது ஒரே மல்லி).

இங்கே ஏற்கிழிக்கும் நோய்த் திஞ்டுக்காக விளையังிப்பு!

சமப்பட்ட ஓவரில்
--------------------------------------------------

[ta_safety] ✅ | Char: 10%, Word: 6%
  Output: கர்ப்ரதிநூறவங்க: 1) "மஞ்சம்" (the glory of the Lord). 2) "ஆபரிமருளம்" - 30 days. 3) "அழுத்தம்" or "இலவசம்". This means that there will be a long period in which this power is not available. So, when w
--------------------------------------------------

[ta_culture] ✅ | Char: 75%, Word: 83%
  Output: இவர் அனைத்தும், இயச்சியன். நாட்டின் உண்மைகளின்

பழையின் 'கஷ்஠ு' - 1980-ஆம், 25-அமைதல்.

என்று ஒரு விழிப்புரிமை எண்ணிக்கில்லென்றால் என்ன? ஏன் தன் �
--------------------------------------------------

[ta_legal] ✅ | Char: 19%, Word: 14%
  Output: நிறும்பரப், FIR (First Information Report) அனையரின் கலாசாகம். FIR மூலம் இருக்கியாளர் தொடர்வில் ஆழும்.

FIR உண்டறையின்

1. 90-360 days from the date of filing for FIR to be heard within this period.
2.
--------------------------------------------------

[ta_greeting] ✅ | Char: 24%, Word: 19%
  Output: பிருதம்: பொறி + 180°, சான்றம்: 2-3 நடையள், முழுமை: 5-7%, வருமான்:

- 4% (P/E = 4/2 = 2))
- 6% (P/Q = 6/3 = 2)))
- 9% (P/S = 9/3 = #))
ஆலணம்:
- P/E=2 → 4%
- P/Q=2 →6%
- P/S=#→9%

இது P
--------------------------------------------------

📊 v5.3 Instruction baseline: 9/9 non-empty responses

In [12]:
# Cell 9 — Calculate Training Steps

# Re-enable gradient checkpointing for training
model.gradient_checkpointing_enable()
model.config.use_cache = False
model.train()

tokens_per_step = BATCH_SIZE * max(n_gpus, 1) * MAX_SEQ_LENGTH * GRADIENT_ACCUMULATION
steps_per_epoch = len(train_dataset) // (BATCH_SIZE * max(n_gpus, 1) * GRADIENT_ACCUMULATION)
total_steps = steps_per_epoch * NUM_EPOCHS
total_tokens_trained = total_steps * tokens_per_step

# Save/log intervals
save_steps = max(total_steps // 5, 50)     # ~5 checkpoints
log_steps = max(total_steps // 40, 10)     # ~40 log entries

print(f"\U0001f4ca Training Plan:")
print(f"   Dataset blocks:      {len(train_dataset):,}")
print(f"   Tokens/step:         {tokens_per_step:,}")
print(f"   Steps/epoch:         {steps_per_epoch:,}")
print(f"   Total steps:         {total_steps:,}")
print(f"   Tokens trained:      {total_tokens_trained:,}")
print(f"   Save every:          {save_steps} steps")
print(f"   Log every:           {log_steps} steps")

# Sanity check
if total_steps < 100:
    print(f"   \u26a0\ufe0f Only {total_steps} steps \u2014 consider reducing batch size")
elif total_steps > 2000:
    print(f"   \u26a0\ufe0f {total_steps} steps \u2014 may be slow, consider increasing batch size")
else:
    print(f"   \u2705 Step count looks good for ~15M tokens")

📊 Training Plan:
   Dataset blocks:      4,683
   Tokens/step:         16,384
   Steps/epoch:         292
   Total steps:         292
   Tokens trained:      4,784,128
   Save every:          58 steps
   Log every:           10 steps
   ✅ Step count looks good for ~15M tokens

In [13]:
# Cell 10 — Training Setup

class LossLoggingCallback(TrainerCallback):
    def __init__(self):
        self.losses = []

    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and "loss" in logs:
            step = state.global_step
            loss = logs["loss"]
            lr = logs.get("learning_rate", 0)
            self.losses.append((step, loss))
            print(f"  Step {step:4d}/{total_steps} | Loss: {loss:.4f} | LR: {lr:.2e}")

loss_callback = LossLoggingCallback()

OUTPUT_DIR = "./dapt-v2_0"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION,
    learning_rate=LEARNING_RATE,
    lr_scheduler_type="cosine",
    warmup_ratio=WARMUP_RATIO,
    logging_steps=log_steps,
    save_steps=save_steps,
    save_total_limit=3,
    fp16=True,
    bf16=False,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    max_grad_norm=1.0,
    optim="adamw_torch",
    report_to="none",
    seed=RANDOM_SEED,
    load_best_model_at_end=False,
    dataloader_pin_memory=True,
    hub_model_id=OUTPUT_ADAPTER,
    push_to_hub=True,
    hub_strategy="checkpoint",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    data_collator=PackedDataCollator(),
    callbacks=[loss_callback],
)

print("\u2705 Trainer ready")
print(f"   Steps: ~{total_steps} | LR: {LEARNING_RATE} | Effective BS: {effective_batch}")
print(f"   fp16: True | grad_ckpt: True | optimizer: AdamW")
print(f"   Hub push: {OUTPUT_ADAPTER} (checkpoint strategy)")

✅ Trainer ready
   Steps: ~292 | LR: 1e-05 | Effective BS: 16
   fp16: True | grad_ckpt: True | optimizer: AdamW
   Hub push: CryptoYogi/vazhi-v5_3-dapt-lora (checkpoint strategy)

In [14]:
# Cell 11 — Train

print("\U0001f680 Starting Clean DAPT v2.0 training...")
print(f"   ~{total_steps} steps, LR={LEARNING_RATE}, fp16=True")
print(f"   Base: v5.3 SFT model (incremental DAPT)")
print(f"   Tokens: ~{total_tokens_trained / 1e6:.0f}M")
print()

train_result = trainer.train()

print("\n\u2705 Training complete!")
metrics = train_result.metrics
for k, v in metrics.items():
    print(f"   {k}: {v}")

# Loss summary
if loss_callback.losses:
    start_loss = loss_callback.losses[0][1]
    end_loss = loss_callback.losses[-1][1]
    print(f"\n\U0001f4c8 Loss: {start_loss:.4f} \u2192 {end_loss:.4f} ({100*(start_loss - end_loss)/start_loss:.1f}% drop)")

# Save final adapter
trainer.save_model()
trainer.push_to_hub()

🚀 Starting Clean DAPT v2.0 training...
   ~292 steps, LR=1e-05, fp16=True
   Base: v5.3 SFT model (incremental DAPT)
   Tokens: ~5M

  Step   10/292 | Loss: 1.2253 | LR: 6.00e-06
  Step   20/292 | Loss: 1.2034 | LR: 9.99e-06
  Step   30/292 | Loss: 1.1584 | LR: 9.94e-06
  Step   40/292 | Loss: 1.1845 | LR: 9.82e-06
  Step   50/292 | Loss: 1.1227 | LR: 9.64e-06
  Step   60/292 | Loss: 1.1104 | LR: 9.39e-06
  Step   70/292 | Loss: 1.1034 | LR: 9.10e-06
  Step   80/292 | Loss: 1.1158 | LR: 8.75e-06
  Step   90/292 | Loss: 1.0973 | LR: 8.35e-06
  Step  100/292 | Loss: 1.1051 | LR: 7.91e-06
  Step  110/292 | Loss: 1.0709 | LR: 7.43e-06
  Step  120/292 | Loss: 1.0804 | LR: 6.93e-06
  Step  130/292 | Loss: 1.0757 | LR: 6.39e-06
  Step  140/292 | Loss: 1.0637 | LR: 5.84e-06
  Step  150/292 | Loss: 1.0777 | LR: 5.28e-06
  Step  160/292 | Loss: 1.0383 | LR: 4.72e-06
  Step  170/292 | Loss: 1.0394 | LR: 4.16e-06
  Step  180/292 | Loss: 1.0627 | LR: 3.61e-06
  Step  190/292 | Loss: 1.0595 | LR: 3.07e-06
  Step  200/292 | Loss: 1.0549 | LR: 2.57e-06
  Step  210/292 | Loss: 1.0539 | LR: 2.09e-06
  Step  220/292 | Loss: 1.0606 | LR: 1.65e-06
  Step  230/292 | Loss: 1.0735 | LR: 1.25e-06
  Step  240/292 | Loss: 1.0343 | LR: 9.02e-07
  Step  250/292 | Loss: 1.0488 | LR: 6.05e-07
  Step  260/292 | Loss: 1.0440 | LR: 3.65e-07
  Step  270/292 | Loss: 1.0785 | LR: 1.83e-07
  Step  280/292 | Loss: 1.0745 | LR: 6.24e-08
  Step  290/292 | Loss: 1.0482 | LR: 5.11e-09

✅ Training complete!
   train_runtime: 1388.7616
   train_samples_per_second: 3.372
   train_steps_per_second: 0.211
   total_flos: 1.296367091712e+16
   train_loss: 1.0882427993487986
   epoch: 1.0

📈 Loss: 1.2253 → 1.0482 (14.5% drop)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...pt-v2_0/training_args.bin: 100%|##########| 5.84kB / 5.84kB

  ...adapter_model.safetensors: 100%|##########| 40.4MB / 40.4MB

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...pt-v2_0/training_args.bin: 100%|##########| 5.84kB / 5.84kB

  ...adapter_model.safetensors: 100%|##########| 40.4MB / 40.4MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt-lora/commit/6563d4eabae4fa43dfdcdab51c58cdf1107953d2', commit_message='End of training', commit_description='', oid='6563d4eabae4fa43dfdcdab51c58cdf1107953d2', pr_url=None, repo_url=RepoUrl('https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt-lora', endpoint='https://huggingface.co', repo_type='model', repo_id='CryptoYogi/vazhi-v5_3-dapt-lora'), pr_revision=None, pr_num=None)

In [15]:
# Cell 12 — Resume Cell (Colab Disconnect Recovery)
# ONLY run this cell if training was interrupted. Skip if training completed above.

# === UNCOMMENT AND RUN ONLY IF TRAINING WAS INTERRUPTED ===
# checkpoints = sorted(glob.glob(f"{OUTPUT_DIR}/checkpoint-*"), key=os.path.getmtime)
# if checkpoints:
#     latest_ckpt = checkpoints[-1]
#     print(f"\U0001f504 Resuming from {latest_ckpt}")
#     train_result = trainer.train(resume_from_checkpoint=latest_ckpt)
#     print("\u2705 Training resumed and completed!")
#     metrics = train_result.metrics
#     for k, v in metrics.items():
#         print(f"   {k}: {v}")
#     trainer.save_model()
#     trainer.push_to_hub()
# else:
#     print("\u274c No checkpoints found. Run training from scratch (Cell 11).")

In [19]:
  # Cell 11b — Interim Eval (run AFTER Cell 11, BEFORE Cell 13)
  # Quick Tamil quality check on the LoRA model before deciding on more epochs

  model.gradient_checkpointing_disable()
  model.config.use_cache = True
  model.eval()

  print(f"{'='*60}")
  print(f"🧪 INTERIM EVAL after Epoch 1")
  print(f"{'='*60}")

  interim_results = []
  for category, prompt_text in TAMIL_EVAL_PROMPTS:
      response = generate_tamil(model, tokenizer, prompt_text)
      t_pct = tamil_char_pct(response)
      tamil_words, total_words = count_tamil_words(response)
      word_pct = 100.0 * tamil_words / max(total_words, 1)
      interim_results.append({'category': category, 'tamil_word_pct': word_pct})

      print(f"\n[{category.upper()}] Char: {t_pct:.0f}%, Word: {word_pct:.0f}%")
      print(f"  Output: {response[:200]}")

  avg_word = np.mean([r['tamil_word_pct'] for r in interim_results])
  print(f"\n📊 Epoch 1: avg word {avg_word:.0f}% (baseline was {avg_pre_word:.0f}%)")
  print(f"   Δ = {avg_word - avg_pre_word:+.0f}%")
  print(f"\n→ If improving, run Cell 11c for another epoch")
  print(f"→ If plateaued or degrading, skip to Cell 13 (merge)")

============================================================
🧪 INTERIM EVAL after Epoch 1
============================================================

[PROSE] Char: 87%, Word: 100%
  Output: இங்கு வீழ்ச்சி,சலுப்புற்று உண்ணும் என்றால்,அது ஏனோ?என்றுகூட எனக்குத் தாமாயிர் ஜாரர் இப்படி கொண்டிருக்கிறார்கள்.

பிரதேஸ்வர வேறு உதவிகள்

மனித

[CULTURE] Char: 86%, Word: 100%
  Output: தனவே, படையாற்றுக்வி என்பது ஒரு சிலசஞ் சாரணத்தை உருவாக்குகிறது.இந்த ஆண்டு அழைத்ததன் அடிப்படோம்.அப்படி வந்ணி அறிவியல், ஓரணும் ஏன்! மட்டுமே ஜ

[LITERATURE] Char: 79%, Word: 82%
  Output: பாதித்தகட்டும். ஆனால் உயிருடனும் ஒன்னுசத்திலும் – 'எழுத்த நீங்கள்' எனவும், 'இரண்டு வாரங்சாலும்', எனக்கோர முயற்சி. 7-10ஆம் ஆண்டில் இதுவரை ஏழுக்கு �

[KNOWLEDGE] Char: 85%, Word: 100%
  Output: த்தைப் பற்றி உணர்வாள்ளி இல்லை.இயற்சியாக நடங்கும் ஒரு அழகான ஆணையோ, ஏதொரு ரூபமாகிவிடும்!அதே ஒரே அழல் அழவிடுவது, உஷ்ணமை இருக்குவதற்கு உஞ்�

[DAILY] Char: 82%, Word: 94%
  Output: , 2017-ஆனங்கள் பரபரவணி. உடல் ஒற்றோராக இருநாள்ஜீவியின் வெற்றி அளவு சாதாரண ஊழியர் ஏற்றுப் பூச்சர் மற்றவர்களுக்கு ரீதி கொண்டிருக்ஷேயம்.

இல்ளி�

📊 Epoch 1: avg word 95% (baseline was 76%)
   Δ = +19%

→ If improving, run Cell 11c for another epoch
→ If plateaued or degrading, skip to Cell 13 (merge)

In [21]:
  # Cell 11c — Train Epoch 2 (fresh cosine LR cycle)

  model.gradient_checkpointing_enable()
  model.config.use_cache = False
  model.train()

  loss_callback_e2 = LossLoggingCallback()

  trainer_e2 = Trainer(
      model=model,
      args=TrainingArguments(
          output_dir=OUTPUT_DIR,
          num_train_epochs=1,
          per_device_train_batch_size=BATCH_SIZE,
          gradient_accumulation_steps=GRADIENT_ACCUMULATION,
          learning_rate=LEARNING_RATE,
          lr_scheduler_type="cosine",
          warmup_ratio=WARMUP_RATIO,
          logging_steps=log_steps,
          save_steps=save_steps,
          save_total_limit=3,
          fp16=True,
          gradient_checkpointing=True,
          gradient_checkpointing_kwargs={"use_reentrant": False},
          max_grad_norm=1.0,
          optim="adamw_torch",
          report_to="none",
          seed=RANDOM_SEED,
          dataloader_pin_memory=True,
          hub_model_id=OUTPUT_ADAPTER,
          push_to_hub=True,
          hub_strategy="checkpoint",
      ),
      train_dataset=train_dataset,
      data_collator=PackedDataCollator(),
      callbacks=[loss_callback_e2],
  )

  print("🚀 Starting Epoch 2 (fresh cosine LR cycle)...")
  train_result = trainer_e2.train()

  print(f"\n✅ Epoch 2 complete!")
  for k, v in train_result.metrics.items():
      print(f"   {k}: {v}")

  if loss_callback_e2.losses:
      s = loss_callback_e2.losses[0][1]
      e = loss_callback_e2.losses[-1][1]
      print(f"\n📈 Epoch 2 loss: {s:.4f} → {e:.4f} ({100*(s-e)/s:.1f}% drop)")

  trainer_e2.save_model()
  trainer_e2.push_to_hub()

🚀 Starting Epoch 2 (fresh cosine LR cycle)...

  Step   10/292 | Loss: 1.0249 | LR: 6.00e-06
  Step   20/292 | Loss: 1.0303 | LR: 9.99e-06
  Step   30/292 | Loss: 1.0186 | LR: 9.94e-06
  Step   40/292 | Loss: 1.0634 | LR: 9.82e-06
  Step   50/292 | Loss: 1.0150 | LR: 9.64e-06
  Step   60/292 | Loss: 1.0149 | LR: 9.39e-06
  Step   70/292 | Loss: 1.0164 | LR: 9.10e-06
  Step   80/292 | Loss: 1.0365 | LR: 8.75e-06
  Step   90/292 | Loss: 1.0230 | LR: 8.35e-06
  Step  100/292 | Loss: 1.0349 | LR: 7.91e-06
  Step  110/292 | Loss: 1.0062 | LR: 7.43e-06
  Step  120/292 | Loss: 1.0184 | LR: 6.93e-06
  Step  130/292 | Loss: 1.0171 | LR: 6.39e-06
  Step  140/292 | Loss: 1.0071 | LR: 5.84e-06
  Step  150/292 | Loss: 1.0238 | LR: 5.28e-06
  Step  160/292 | Loss: 0.9877 | LR: 4.72e-06
  Step  170/292 | Loss: 0.9893 | LR: 4.16e-06
  Step  180/292 | Loss: 1.0130 | LR: 3.61e-06
  Step  190/292 | Loss: 1.0108 | LR: 3.07e-06
  Step  200/292 | Loss: 1.0054 | LR: 2.57e-06
  Step  210/292 | Loss: 1.0077 | LR: 2.09e-06
  Step  220/292 | Loss: 1.0139 | LR: 1.65e-06
  Step  230/292 | Loss: 1.0282 | LR: 1.25e-06
  Step  240/292 | Loss: 0.9889 | LR: 9.02e-07
  Step  250/292 | Loss: 1.0018 | LR: 6.05e-07
  Step  260/292 | Loss: 0.9997 | LR: 3.65e-07
  Step  270/292 | Loss: 1.0316 | LR: 1.83e-07
  Step  280/292 | Loss: 1.0293 | LR: 6.24e-08
  Step  290/292 | Loss: 1.0040 | LR: 5.11e-09

✅ Epoch 2 complete!
   train_runtime: 1387.6429
   train_samples_per_second: 3.375
   train_steps_per_second: 0.211
   total_flos: 1.296367091712e+16
   train_loss: 1.01600297563312
   epoch: 1.0

📈 Epoch 2 loss: 1.0249 → 1.0040 (2.0% drop)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...pt-v2_0/training_args.bin: 100%|##########| 5.84kB / 5.84kB

  ...adapter_model.safetensors: 100%|##########| 40.4MB / 40.4MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...pt-v2_0/training_args.bin: 100%|##########| 5.84kB / 5.84kB

  ...adapter_model.safetensors: 100%|##########| 40.4MB / 40.4MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt-lora/commit/76019b2f0fb56e63a359d08bafb898405b899664', commit_message='End of training', commit_description='', oid='76019b2f0fb56e63a359d08bafb898405b899664', pr_url=None, repo_url=RepoUrl('https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt-lora', endpoint='https://huggingface.co', repo_type='model', repo_id='CryptoYogi/vazhi-v5_3-dapt-lora'), pr_revision=None, pr_num=None)

In [22]:
  # Cell 11b — Interim Eval (run AFTER Cell 11, BEFORE Cell 13)
  # Quick Tamil quality check on the LoRA model before deciding on more epochs

  model.gradient_checkpointing_disable()
  model.config.use_cache = True
  model.eval()

  print(f"{'='*60}")
  print(f"🧪 INTERIM EVAL after Epoch 2")
  print(f"{'='*60}")

  interim_results = []
  for category, prompt_text in TAMIL_EVAL_PROMPTS:
      response = generate_tamil(model, tokenizer, prompt_text)
      t_pct = tamil_char_pct(response)
      tamil_words, total_words = count_tamil_words(response)
      word_pct = 100.0 * tamil_words / max(total_words, 1)
      interim_results.append({'category': category, 'tamil_word_pct': word_pct})

      print(f"\n[{category.upper()}] Char: {t_pct:.0f}%, Word: {word_pct:.0f}%")
      print(f"  Output: {response[:200]}")

  avg_word = np.mean([r['tamil_word_pct'] for r in interim_results])
  print(f"\n📊 Epoch 2: avg word {avg_word:.0f}% (baseline was {avg_pre_word:.0f}%)")
  print(f"   Δ = {avg_word - avg_pre_word:+.0f}%")
  print(f"\n→ If improving, run Cell 11c for another epoch")
  print(f"→ If plateaued or degrading, skip to Cell 13 (merge)")

============================================================
🧪 INTERIM EVAL after Epoch 2
============================================================

[PROSE] Char: 81%, Word: 100%
  Output: இங்கு வீடு, சலி எப்படிற்கும் ரசயம்

ஆண்டு 10-அறுதிப்படுத்துதல்: உஷ்ணார் வழிகாட்டுதலை ஏற்பட்டால்...இது ஐஸ்ஸியர் ஜோர்ஜர் தகுதி! (அத்திரயிரியஞ்)

எனக்�

[CULTURE] Char: 84%, Word: 94%
  Output: தனவெறி வேண்டிய அழகு,அசத்சய்,ஓடிப் போனாளர் என்று உறுதி ஏற்படுகிறது.

ஆனால் ஒவ்வொரு லீனர் ஓய்ஸ்ட்ஜி (ஈ) மூலம் ஒரு அற்புத முறையான துற்றம் பிள்ளை

[LITERATURE] Char: 79%, Word: 89%
  Output: பதி நாடகம் வழங்கப்பட்டது. 2019ஆம் ஆண்துறையில் உலகத்தின் ஒரு சத்குழு (சத்ரஞ்சம்) போல ஏற்கனவே, "இளநுரீ" - இந்த நஷ்டத்தை உருவாக்கும் ஒன்றாக, பி�

[KNOWLEDGE] Char: 86%, Word: 100%
  Output: த்தைப் பற்றி உண்டாய்.இந்த வழிகள், ஆலோசிரியங்கள் சாதாரணமாகவே அடையாளம் ஏற்பட்டிருக்கும்.

அது ஒரு ஜீவரும் மஹஸ்ஸ்ளானில் வைத்திருந்நுட்டி, "என

[DAILY] Char: 84%, Word: 92%
  Output: , 2017-ஆனங்களுடன் இரண்டு பெண்ணாவசி அறிவுபூஜியாள் உருவாக்கப்பட்டிருநாளோ! ஏனென்றால், "ஒவ்வொரு சின்ன ஜீவனும்" என்று ஓரண்ணமாக சொல்கிறார்கள

📊 Epoch 2: avg word 95% (baseline was 76%)
   Δ = +19%

→ If improving, run Cell 11c for another epoch
→ If plateaued or degrading, skip to Cell 13 (merge)

In [23]:
# Cell 13 — Save Adapter + Merge to fp16
# CRITICAL: Merge in fp16, NEVER into 4-bit (lesson from v3.6)

ADAPTER_PATH = "./dapt-v2_0-lora"

print("\U0001f4be Saving LoRA adapter...")
trainer.save_model(ADAPTER_PATH)
tokenizer.save_pretrained(ADAPTER_PATH)

adapter_files = glob.glob(f"{ADAPTER_PATH}/*")
print(f"   Files: {[os.path.basename(f) for f in adapter_files]}")
assert any('adapter' in f for f in adapter_files), "No adapter files!"
print("\u2705 Adapter saved")

# Upload adapter backup
api = HfApi()
api.create_repo(OUTPUT_ADAPTER, exist_ok=True)
print(f"\U0001f4e4 Uploading adapter to {OUTPUT_ADAPTER}...")
api.upload_folder(
    folder_path=ADAPTER_PATH,
    repo_id=OUTPUT_ADAPTER,
    commit_message=f"Clean DAPT v2.0 adapter: own sources, Tamil>=90%, r={LORA_R}, lr={LEARNING_RATE}",
)
print(f"\u2705 Adapter uploaded: https://huggingface.co/{OUTPUT_ADAPTER}")

# Free training model for merge
del model
del trainer
gc.collect()
torch.cuda.empty_cache()
print("\U0001f5d1\ufe0f Training model freed")

# Reload fresh base in fp16 for clean merge
print(f"\n\U0001f517 Loading fresh {BASE_MODEL} in fp16 for merge...")
base_model_fp16 = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map={"":0},
    trust_remote_code=True,
)

peft_model = PeftModel.from_pretrained(base_model_fp16, ADAPTER_PATH)
peft_model.gradient_checkpointing_disable()
peft_model.config.use_cache = True
peft_model.eval()

print("\U0001f500 Merging LoRA in fp16...")
merged_model = peft_model.merge_and_unload()
print(f"\u2705 Merged: {merged_model.num_parameters():,} params")

💾 Saving LoRA adapter...

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors: 100%|##########| 40.4MB / 40.4MB

  ...pt-v2_0/training_args.bin: 100%|##########| 5.84kB / 5.84kB

   Files: ['merges.txt', 'special_tokens_map.json', 'adapter_model.safetensors', 'chat_template.jinja', 'adapter_config.json', 'vocab.json', 'added_tokens.json', 'tokenizer.json', 'tokenizer_config.json', 'training_args.bin', 'README.md']
✅ Adapter saved
📤 Uploading adapter to CryptoYogi/vazhi-v5_3-dapt-lora...

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ..._0-lora/training_args.bin: 100%|##########| 5.84kB / 5.84kB

  ...adapter_model.safetensors: 100%|##########| 40.4MB / 40.4MB

  ...-v2_0-lora/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

✅ Adapter uploaded: https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt-lora
🗑️ Training model freed

🔗 Loading fresh CryptoYogi/vazhi-v5_3 in fp16 for merge...
🔀 Merging LoRA in fp16...
✅ Merged: 596,049,920 params

In [24]:
# Cell 14 — Post-Training Eval: Tamil Quality
# Same 5 Tamil prompts as Cell 7. Compare Tamil char %, word quality, coherence.
# Success criteria: Tamil quality improves (more real words, less made-up words)

merged_model.eval()
merged_model.config.use_cache = True

# Clear suppress_tokens
if hasattr(merged_model.config, 'suppress_tokens'):
    merged_model.config.suppress_tokens = None
if hasattr(merged_model, 'generation_config') and hasattr(merged_model.generation_config, 'suppress_tokens'):
    merged_model.generation_config.suppress_tokens = None

print(f"{'='*60}")
print(f"\U0001f9ea POST-DAPT EVAL: Tamil Quality")
print(f"{'='*60}")

post_tamil_results = []

for category, prompt_text in TAMIL_EVAL_PROMPTS:
    response = generate_tamil(merged_model, tokenizer, prompt_text)
    t_pct = tamil_char_pct(response)
    tamil_words, total_words = count_tamil_words(response)
    word_pct = 100.0 * tamil_words / max(total_words, 1)

    post_tamil_results.append({
        'category': category,
        'prompt': prompt_text,
        'response': response[:300],
        'tamil_char_pct': t_pct,
        'tamil_word_pct': word_pct,
    })

    print(f"\n[{category.upper()}] Char: {t_pct:.0f}%, Word: {word_pct:.0f}%")
    print(f"  Prompt: {prompt_text[:60]}")
    print(f"  Output: {response[:200]}")
    print("-" * 50)

avg_post_char = np.mean([r['tamil_char_pct'] for r in post_tamil_results])
avg_post_word = np.mean([r['tamil_word_pct'] for r in post_tamil_results])

print(f"\n\U0001f4ca Post-DAPT Tamil: avg char {avg_post_char:.0f}%, avg word {avg_post_word:.0f}%")
print(f"   vs Pre-DAPT:    avg char {avg_pre_char:.0f}%, avg word {avg_pre_word:.0f}%")
print(f"   Change:         char {avg_post_char - avg_pre_char:+.0f}%, word {avg_post_word - avg_pre_word:+.0f}%")

============================================================
🧪 POST-DAPT EVAL: Tamil Quality
============================================================

[PROSE] Char: 80%, Word: 87%
  Prompt: தமிழ்நாடு இந்தியாவின் தென் பகுதியில் அமைந்துள்ள ஒரு மாநிலம்.
  Output: இங்கு 18,096 சதவிகிதங்றலோர் (பக்ரச் ஜனவரி) வரையில் 43% எண்ணமுறையான உயர்ந்த ஊழியர் வாழும்.

அமூதிப்படுத்தப்பட்ட நீதன்கள்

ஆலோசனை ஏற்படியிருந்நி�
--------------------------------------------------

[CULTURE] Char: 83%, Word: 89%
  Prompt: பொங்கல் தமிழர்களின் முக்கிய திருநாள்.
  Output: வன்வடிவங்சி பதற்றம்

ஒரு ஆசூரண இயைக்காதீர்ஃஇன்னும் உங்வாழ்வு, அழகஞ் டாலும்; எனக்கோடு - உந்துக்ஷில் நின்று அழும்.

அவனை ஏதோ ஜீவன் பாதித்து �
--------------------------------------------------

[LITERATURE] Char: 82%, Word: 94%
  Prompt: வள்ளுவர் கூறிய அறம், பொருள், இன்பம் என்ற மூன்று
  Output: க் காலத்தில் சட்டப்பயண நிருபரங்களின் ஒரு வழி, "ஓசிஸ்" (சமையற்ற) உணர்ச்சி.அப்படியெல்லாம் நீங்ஜோனில்

ஷேல் சாலையில் -இந்த குறிப்பான அர்த்தம்! �
--------------------------------------------------

[KNOWLEDGE] Char: 78%, Word: 94%
  Prompt: சித்த மருத்துவம் என்பது தமிழ் மக்களின் பாரம்பரிய
  Output: த்தைப் பற்றி சில அடிப்படையான நிலையிட்டு, "இல்லை" இழைக்கு ஒரு விருப்பம் ஏற்பட வேண்டுமா?

அங்கீகரித்யன்: 7.481235

என்று ஆன்மூலத்தில் உட்பட்ட இயல
--------------------------------------------------

[DAILY] Char: 84%, Word: 94%
  Prompt: காலையில் எழுந்ததும் முதலில்
  Output: , வரச்சன் (வறுப்பி) உள்ள கண்ணீட், அவர் இரண்டாவது ஆனந்யாயம் ஏற்றுவது. ஒரு நோயுடன் ஒரே நூல் ஊக்குவாக உளிர்ச்சியுள்ளது.

எடுத்துக்கொண்ட குறிப்பிட்ட
--------------------------------------------------

📊 Post-DAPT Tamil: avg char 81%, avg word 92%
   vs Pre-DAPT:    avg char 61%, avg word 76%
   Change:         char +20%, word +16%

In [25]:
# Cell 15 — Post-Training Eval: Instruction Following + SFT Behavior
# Same prompts as Cell 8 (English + Tamil domain-specific). Compare coherence and format.
# Success criteria: Instruction following AND SFT behavior NOT degraded.

print(f"{'='*60}")
print(f"\U0001f9ea POST-DAPT EVAL: Instruction Following + SFT Behavior")
print(f"{'='*60}")

post_instruct_results = []

for category, prompt_text in INSTRUCTION_EVAL_PROMPTS:
    response = generate_tamil(merged_model, tokenizer, prompt_text)
    t_pct = tamil_char_pct(response)
    tamil_words, total_words = count_tamil_words(response)
    word_pct = 100.0 * tamil_words / max(total_words, 1)
    is_empty = len(response.strip()) < 10
    has_structure = any(kw in response for kw in ['\n', '.', ':', '-', '\u0bcd'])

    post_instruct_results.append({
        'category': category,
        'prompt': prompt_text,
        'response': response[:300],
        'tamil_char_pct': t_pct,
        'tamil_word_pct': word_pct,
        'is_empty': is_empty,
        'has_structure': has_structure,
    })

    status = "\u274c EMPTY" if is_empty else "\u2705"
    print(f"\n[{category}] {status} | Char: {t_pct:.0f}%, Word: {word_pct:.0f}%")
    print(f"  Output: {response[:200]}")
    print("-" * 50)

post_non_empty = sum(1 for r in post_instruct_results if not r['is_empty'])
pre_non_empty = sum(1 for r in pre_instruct_results if not r['is_empty'])

print(f"\n\U0001f4ca Post-DAPT Instruction: {post_non_empty}/{len(post_instruct_results)} non-empty")
print(f"   vs Pre-DAPT:          {pre_non_empty}/{len(pre_instruct_results)} non-empty")

if post_non_empty < pre_non_empty * 0.7:
    print(f"   \u274c DAPT degraded instruction following! Consider lower LR or fewer steps.")
else:
    print(f"   \u2705 Instruction following preserved")

============================================================
🧪 POST-DAPT EVAL: Instruction Following + SFT Behavior
============================================================

[en_instruct] ✅ | Char: 0%, Word: 0%
  Output: tamilnadu's capital city is warangalinga, located in tamil nadu. it has a very good infrastructure with modern roads and bridges.

warangala town also includes several cultural landmarks such as the f
--------------------------------------------------

[en_instruct] ✅ | Char: 0%, Word: 0%
  Output: utterance
Okay, the user wants an explanation of Pongal in a single paragraph.

First, I need to mention the main dates: 30th and 21st. Then explain that it's celebrated by families gathering for food
--------------------------------------------------

[en_safety] ✅ | Char: 0%, Word: 0%
  Output: employer can't be hacked through any means. The only way to get money out of an employer is by fraud, identity theft or other fraudulent methods.
If you are a victim and have been targeted for financi
--------------------------------------------------

[ta_health] ✅ | Char: 74%, Word: 81%
  Output: உடல் தேவைப்படக்கூடியது: 1) மண்ணம், 2) சுழற்றம் (அரசு), 3) வெளி ஒரு கிராமம். ஏனென்றால், அது கடும்.

இலவச லங்கள் - அற்குறி

ஒருவர் உடலுடனும் ஓட்டாத
--------------------------------------------------

[ta_govt] ✅ | Char: 86%, Word: 100%
  Output: கடலில் உளவிதமானது.சூழப்பு, அடையாள நிறைவு, முஸ்ஸி ஏற்படுத்தலும் ஒரு ஊர்கள் என சீட்டிருக்கிறது.

ஆனால் கடலோடு இருந்தாலும்வேறே ஜிங்குகள் இரண்ட�
--------------------------------------------------

[ta_safety] ✅ | Char: 80%, Word: 78%
  Output: பிரதை, உளவரகத்தில் பற்றிய மனங்களை அழைப்பது ஒன்று. உஷ்஠ிள் ஏற்கொண்ட ஓயிர சூழ்நிலைகளைப் போன்ற விழிப்புணர்வு - அஞ்சத்தீர்ப்போது

(1) 7-8 வயது �
--------------------------------------------------

[ta_culture] ✅ | Char: 80%, Word: 94%
  Output: படித்தனம் இரண்டு வயத்களைச் செலவிய நாள் உடல் மீது. அழகான ஒரு நஷ்டையின் எல்லாவற்றை ஏதோ, ஓட்டின் 10-20% விண்ணாரியம்.

இஞ்சுவியன் வீதிக் குளிர்�
--------------------------------------------------

[ta_legal] ✅ | Char: 62%, Word: 60%
  Output: காலம்: 2-3 மணிந்திரசரிகளுக்கு, 10-25 ஆயுத அழகற்சை. வங்கன்: 4-8 ஏழுக்ஷஸியா (1ஆம்), உலகார்விலே: 6-12 ஜனகத்தின். டாலூப்: 9-14 ஓய்ண வளங்று - 7-10 பத
--------------------------------------------------

[ta_greeting] ✅ | Char: 82%, Word: 100%
  Output: நீ எனது "பலித்தர்" மற்றும் "அளவுகொடி" (ஆய்) போது, ஒரு வழியில் இங்கெல்லாம் அளவுசூர்டம் செய்யுங்தால். உங்னு சொல்ல ஏற்கின்ற ஐந்து பக்ஷம் பிரிய
--------------------------------------------------

📊 Post-DAPT Instruction: 9/9 non-empty
   vs Pre-DAPT:          9/9 non-empty
   ✅ Instruction following preserved

In [26]:
# Cell 16 — Side-by-Side Comparison Table

print("=" * 80)
print("\U0001f4ca SIDE-BY-SIDE: v5.3 (Pre-DAPT) vs DAPT v2.0 (Post-DAPT)")
print("=" * 80)

# Tamil quality comparison
print(f"\n--- Tamil Quality (text continuation) ---")
print(f"{'Category':<12} {'Pre Char%':>10} {'Post Char%':>11} {'Pre Word%':>10} {'Post Word%':>11} {'Winner':>8}")
print("-" * 75)

dapt_wins = 0
for pre, post in zip(pre_tamil_results, post_tamil_results):
    winner = "DAPT" if post['tamil_word_pct'] > pre['tamil_word_pct'] + 5 else (
        "v5.3" if pre['tamil_word_pct'] > post['tamil_word_pct'] + 5 else "TIE"
    )
    if post['tamil_word_pct'] > pre['tamil_word_pct']:
        dapt_wins += 1
    print(f"{pre['category']:<12} {pre['tamil_char_pct']:>8.0f}% {post['tamil_char_pct']:>9.0f}% "
          f"{pre['tamil_word_pct']:>8.0f}% {post['tamil_word_pct']:>9.0f}%  {winner:>8}")

print("-" * 75)
print(f"{'AVERAGE':<12} {avg_pre_char:>8.0f}% {avg_post_char:>9.0f}% "
      f"{avg_pre_word:>8.0f}% {avg_post_word:>9.0f}%")

# Instruction following comparison
print(f"\n--- Instruction Following (ChatML prompts) ---")
print(f"{'Category':<15} {'Pre':>12} {'Post':>12}")
print("-" * 45)
for pre, post in zip(pre_instruct_results, post_instruct_results):
    pre_status = "\u2705 response" if not pre['is_empty'] else "\u274c empty"
    post_status = "\u2705 response" if not post['is_empty'] else "\u274c empty"
    print(f"{pre['category']:<15} {pre_status:>12} {post_status:>12}")

# Detailed output comparison
print(f"\n--- Detailed Output Comparison ---")
for pre, post in zip(pre_tamil_results, post_tamil_results):
    print(f"\n\u250c\u2500 [{pre['category'].upper()}] {pre['prompt'][:50]}")
    print(f"\u2502 v5.3:    (Char {pre['tamil_char_pct']:.0f}%, Word {pre['tamil_word_pct']:.0f}%) {pre['response'][:150]}")
    print(f"\u2502 DAPT:    (Char {post['tamil_char_pct']:.0f}%, Word {post['tamil_word_pct']:.0f}%) {post['response'][:150]}")
    print(f"\u2514{'\u2500' * 69}")

# GO/NO-GO verdict
print(f"\n{'='*80}")
print(f"\U0001f3af VERDICT")
print(f"{'='*80}")

tamil_improved = avg_post_word > avg_pre_word
instruct_preserved = post_non_empty >= pre_non_empty * 0.7

if tamil_improved and instruct_preserved:
    print(f"\n\U0001f389 GO \u2014 Tamil quality improved AND instruction following preserved!")
    print(f"   Tamil word%: {avg_pre_word:.0f}% \u2192 {avg_post_word:.0f}% ({avg_post_word - avg_pre_word:+.0f}%)")
    print(f"   Instruct:    {pre_non_empty}/{len(pre_instruct_results)} \u2192 {post_non_empty}/{len(post_instruct_results)}")
    print(f"   \u2192 Upload merged model and evaluate if SFT v5.4 is needed")
elif tamil_improved and not instruct_preserved:
    print(f"\n\u26a0\ufe0f PARTIAL \u2014 Tamil improved but instruction following degraded")
    print(f"   Consider: lower LR, fewer steps, or more chat replay")
    print(f"   \u2192 Upload anyway \u2014 SFT v5.4 will restore instruction following")
elif not tamil_improved and instruct_preserved:
    print(f"\n\u26a0\ufe0f PARTIAL \u2014 Instruction following OK but Tamil didn't improve")
    print(f"   Consider: more tokens, higher LR, or different data")
else:
    print(f"\n\u274c NO-GO \u2014 Both Tamil and instruction following degraded")
    print(f"   DAPT v2.0 failed. Investigate data quality and training params.")

================================================================================
📊 SIDE-BY-SIDE: v5.3 (Pre-DAPT) vs DAPT v2.0 (Post-DAPT)
================================================================================

--- Tamil Quality (text continuation) ---
Category      Pre Char%  Post Char%  Pre Word%  Post Word%   Winner
---------------------------------------------------------------------------
prose              80%        80%       94%        87%      v5.3
culture            72%        83%       91%        89%       TIE
literature         76%        82%      100%        94%      v5.3
knowledge          79%        78%       94%        94%       TIE
daily               0%        84%        0%        94%      DAPT
---------------------------------------------------------------------------
AVERAGE            61%        81%       76%        92%

--- Instruction Following (ChatML prompts) ---
Category                 Pre         Post
---------------------------------------------
en_instruct       ✅ response   ✅ response
en_instruct       ✅ response   ✅ response
en_safety         ✅ response   ✅ response
ta_health         ✅ response   ✅ response
ta_govt           ✅ response   ✅ response
ta_safety         ✅ response   ✅ response
ta_culture        ✅ response   ✅ response
ta_legal          ✅ response   ✅ response
ta_greeting       ✅ response   ✅ response

--- Detailed Output Comparison ---

┌─ [PROSE] தமிழ்நாடு இந்தியாவின் தென் பகுதியில் அமைந்துள்ள ஒர
│ v5.3:    (Char 80%, Word 94%)  3-5 சி, வங்கி/இலவசபூர்ண உயிரிற்குபிறமும் என்று ஏற்பட்டது. அணு வஞ்சான் எழுமா? ஊடிமீது நடநிஶனங்து, உயரம், அறிஞர், இளவு போரங்சே ஒரே ஓரணம் தவ
│ DAPT:    (Char 80%, Word 87%) இங்கு 18,096 சதவிகிதங்றலோர் (பக்ரச் ஜனவரி) வரையில் 43% எண்ணமுறையான உயர்ந்த ஊழியர் வாழும்.

அமூதிப்படுத்தப்பட்ட நீதன்கள்

ஆலோசனை ஏற்படியிருந்நி�
└─────────────────────────────────────────────────────────────────────

┌─ [CULTURE] பொங்கல் தமிழர்களின் முக்கிய திருநாள்.
│ v5.3:    (Char 72%, Word 91%)  இதன் வட்டுவதா? உயர்பழி: 1) அற்சானா! ஒரு ஆண்டு என்று, ஏன் அறில் இன்னை வைச்சு எங்ஙனம், எஞானம் எனில்.

ஆம், 'அரசான' எனக் காரணமா?

இதன் 'எஸ்ஓ ஐஐ-ஐ' �
│ DAPT:    (Char 83%, Word 89%) வன்வடிவங்சி பதற்றம்

ஒரு ஆசூரண இயைக்காதீர்ஃஇன்னும் உங்வாழ்வு, அழகஞ் டாலும்; எனக்கோடு - உந்துக்ஷில் நின்று அழும்.

அவனை ஏதோ ஜீவன் பாதித்து �
└─────────────────────────────────────────────────────────────────────

┌─ [LITERATURE] வள்ளுவர் கூறிய அறம், பொருள், இன்பம் என்ற மூன்று
│ v5.3:    (Char 76%, Word 100%) காலத்தில் ஒப்படி செய்வோ உண்டு? ஏனெน, நாசிரை: "இதை நடக்கவேண்டின்" எனில், உழையில் (அது எண்), எனது ஒரு 5-ஆம் ஐப்புள்ளது. எனவே, சீர்ணிங் ஓய்ஃ "கூட
│ DAPT:    (Char 82%, Word 94%) க் காலத்தில் சட்டப்பயண நிருபரங்களின் ஒரு வழி, "ஓசிஸ்" (சமையற்ற) உணர்ச்சி.அப்படியெல்லாம் நீங்ஜோனில்

ஷேல் சாலையில் -இந்த குறிப்பான அர்த்தம்! �
└─────────────────────────────────────────────────────────────────────

┌─ [KNOWLEDGE] சித்த மருத்துவம் என்பது தமிழ் மக்களின் பாரம்பரிய
│ v5.3:    (Char 79%, Word 94%) ம்

படி 1: இலையறைப்படுத்டுக்கும், செழு-ஆண்ணுக்றோ? அர்வொரு நஷ்டைகளை உள்ளது. ஒவ்வீரும்.

இலை ஏற்பட்டு, ரங்கி ஐடியை விலை என பூச்செயலின் (அ)எல்�
│ DAPT:    (Char 78%, Word 94%) த்தைப் பற்றி சில அடிப்படையான நிலையிட்டு, "இல்லை" இழைக்கு ஒரு விருப்பம் ஏற்பட வேண்டுமா?

அங்கீகரித்யன்: 7.481235

என்று ஆன்மூலத்தில் உட்பட்ட இயல
└─────────────────────────────────────────────────────────────────────

┌─ [DAILY] காலையில் எழுந்ததும் முதலில்
│ v5.3:    (Char 0%, Word 0%)

(1) 60% of the total amount is paid as a commission, and (2) Commission on sales is calculated by multiplying the gross sales price with the coeffic
│ DAPT:    (Char 84%, Word 94%) , வரச்சன் (வறுப்பி) உள்ள கண்ணீட், அவர் இரண்டாவது ஆனந்யாயம் ஏற்றுவது. ஒரு நோயுடன் ஒரே நூல் ஊக்குவாக உளிர்ச்சியுள்ளது.

எடுத்துக்கொண்ட குறிப்பிட்ட
└─────────────────────────────────────────────────────────────────────

================================================================================
🎯 VERDICT
================================================================================

🎉 GO — Tamil quality improved AND instruction following preserved!
   Tamil word%: 76% → 92% (+16%)
   Instruct:    9/9 → 9/9
   → Upload merged model and evaluate if SFT v5.4 is needed

In [27]:
# Cell 17 — Upload Merged Model

api = HfApi()
api.create_repo(OUTPUT_MODEL, exist_ok=True)

print(f"\U0001f4e4 Pushing merged fp16 model to {OUTPUT_MODEL}...")
merged_model.push_to_hub(
    OUTPUT_MODEL,
    private=False,
    commit_message=(
        f"Clean DAPT v2.0: Tamil-adapted v5.3, "
        f"own sources (Sadhguru+classical), Tamil>=90%, "
        f"LoRA r={LORA_R}, lr={LEARNING_RATE}"
    ),
)
tokenizer.push_to_hub(OUTPUT_MODEL)

print(f"\n\u2705 Model:   https://huggingface.co/{OUTPUT_MODEL}")
print(f"\u2705 Adapter: https://huggingface.co/{OUTPUT_ADAPTER}")

📤 Pushing merged fp16 model to CryptoYogi/vazhi-v5_3-dapt...

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...b0coyci/model.safetensors:   4%|3         | 41.9MB / 1.19GB

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpipm7e9y7/tokenizer.json: 100%|##########| 11.4MB / 11.4MB

✅ Model:   https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt
✅ Adapter: https://huggingface.co/CryptoYogi/vazhi-v5_3-dapt-lora

In [28]:
# Cell 18 — Summary

print(f"{'='*60}")
print(f"\U0001f4cb CLEAN DAPT v2.0 \u2014 TRAINING SUMMARY")
print(f"{'='*60}")
print(f"")
print(f"   Lineage:     vanilla \u2192 v5.0 \u2192 v5.1a \u2192 v5.3 \u2192 DAPT v2.0")
print(f"   Base model:  {BASE_MODEL}")
print(f"   Dataset:     {DAPT_DATASET}")
print(f"   Output:      {OUTPUT_MODEL}")
print(f"")
if loss_callback.losses:
    start_loss = loss_callback.losses[0][1]
    end_loss = loss_callback.losses[-1][1]
    print(f"   Loss:        {start_loss:.4f} \u2192 {end_loss:.4f} ({100*(start_loss-end_loss)/start_loss:.1f}% drop)")
print(f"   Steps:       {total_steps}")
print(f"   LR:          {LEARNING_RATE}")
print(f"   LoRA:        r={LORA_R}, alpha={LORA_ALPHA}, modules={len(TARGET_MODULES)}")
print(f"")
print(f"   Tamil quality:")
print(f"     Pre-DAPT:  char {avg_pre_char:.0f}%, word {avg_pre_word:.0f}%")
print(f"     Post-DAPT: char {avg_post_char:.0f}%, word {avg_post_word:.0f}%")
print(f"     Change:    char {avg_post_char - avg_pre_char:+.0f}%, word {avg_post_word - avg_pre_word:+.0f}%")
print(f"")
print(f"   Instruction following:")
print(f"     Pre-DAPT:  {pre_non_empty}/{len(pre_instruct_results)} non-empty")
print(f"     Post-DAPT: {post_non_empty}/{len(post_instruct_results)} non-empty")
print(f"")
print(f"   \U0001f449 Next steps:")
if tamil_improved and instruct_preserved:
    print(f"     1. Evaluate DAPT model manually \u2014 does it produce real Tamil words?")
    print(f"     2. If yes: DAPT v2.0 succeeded! Model may be usable directly.")
    print(f"     3. If format is off: Run SFT v5.4 on top of DAPT model.")
    print(f"     4. GGUF quantization (Q4_K_M) for mobile deployment.")
else:
    print(f"     1. Analyze failure \u2014 check loss curve, data quality")
    print(f"     2. Adjust params: LR, steps, chat replay %")
    print(f"     3. Fallback: Sarvam-1 IQ3_M (1.17GB, proven Tamil)")

print(f"\n| Artifact | Repo | Purpose |")
print(f"|----------|------|---------|")
print(f"| DAPT data | {DAPT_DATASET} | Clean Tamil corpus (own sources, >=90%) |")
print(f"| Merged model | {OUTPUT_MODEL} | DAPT'd v5.3 for eval/deployment |")
print(f"| LoRA adapter | {OUTPUT_ADAPTER} | Recovery backup |")

============================================================
📋 CLEAN DAPT v2.0 — TRAINING SUMMARY
============================================================

   Lineage:     vanilla → v5.0 → v5.1a → v5.3 → DAPT v2.0
   Base model:  CryptoYogi/vazhi-v5_3
   Dataset:     CryptoYogi/vazhi-dapt-tamil-v2_0
   Output:      CryptoYogi/vazhi-v5_3-dapt

   Loss:        1.2253 → 1.0285 (16.1% drop)
   Steps:       292
   LR:          1e-05
   LoRA:        r=16, alpha=32, modules=7

   Tamil quality:
     Pre-DAPT:  char 61%, word 76%
     Post-DAPT: char 81%, word 92%
     Change:    char +20%, word +16%

   Instruction following:
     Pre-DAPT:  9/9 non-empty
     Post-DAPT: 9/9 non-empty

   👉 Next steps:
     1. Evaluate DAPT model manually — does it produce real Tamil words?
     2. If yes: DAPT v2.0 succeeded! Model may be usable directly.
     3. If format is off: Run SFT v5.4 on top of DAPT model.
     4. GGUF quantization (Q4_K_M) for mobile deployment.

| Artifact | Repo | Purpose |
|----------|------|---------|
| DAPT data | CryptoYogi/vazhi-dapt-tamil-v2_0 | Clean Tamil corpus (own sources, >=90%) |
| Merged model | CryptoYogi/vazhi-v5_3-dapt | DAPT'd v5.3 for eval/deployment |
| LoRA adapter | CryptoYogi/vazhi-v5_3-dapt-lora | Recovery backup |